name: Deploy to GCP VM

on:
  push:
    branches:
      - devops/ci-cd/integration

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate to GCP using Workload Identity Federation
      uses: google-github-actions/auth@v1
      with:
        workload_identity_provider: projects/${{ secrets.GCP_PROJECT_NUMBER_TEST }}/locations/global/workloadIdentityPools/github-pool/providers/github-provider
        service_account: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL_TEST }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      

    - name: Deploy to VM
      run: |
        gcloud compute ssh conep-integridad-test-env \
            --zone us-east1-d \
            --project conep-integridad-test \
            --command "bin/bash /home/devops-conep/cer-rd/workflow.sh"
